[package]
name = "project-03-shading"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

glium = { workspace = true }
winit = { workspace = true }
cgmath = { workspace = true }
derive_more = "0.99.18"
