[package]
name = "project-02-transformations"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

glium = { workspace = true }
winit = { workspace = true }
glam = { workspace = true }
