[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = { workspace = true }
winit = { workspace = true }
cgmath = { workspace = true }
image = { workspace = true }
anyhow = { workspace = true }
